"""add login and pass to proxy

Revision ID: 04ec92c79304
Revises: f7e7a2411c0d
Create Date: 2025-10-02 14:57:01.175058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04ec92c79304'
down_revision: Union[str, None] = 'f7e7a2411c0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proxy', sa.Column('login_proxy', sa.String(length=50), nullable=True))
    op.add_column('proxy', sa.Column('pass_proxy', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proxy', 'pass_proxy')
    op.drop_column('proxy', 'login_proxy')
    # ### end Alembic commands ###
