"""add days to proxy table

Revision ID: 34f73f4781fc
Revises: 483cb74db170
Create Date: 2025-06-06 11:36:43.313420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34f73f4781fc'
down_revision: Union[str, None] = '483cb74db170'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proxy', sa.Column('days', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proxy', 'days')
    # ### end Alembic commands ###
