"""add provider to proxy table

Revision ID: 483cb74db170
Revises: e5097488db80
Create Date: 2025-06-06 11:26:12.174437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '483cb74db170'
down_revision: Union[str, None] = 'e5097488db80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proxy', sa.Column('provider', sa.String(length=50), nullable=True))
    op.drop_column('proxy', 'auto_prolong')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proxy', sa.Column('auto_prolong', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('proxy', 'provider')
    # ### end Alembic commands ###
