"""Change proxy table

Revision ID: 50fde4f00b89
Revises: e2c9de7a572f
Create Date: 2025-05-21 13:47:25.763139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50fde4f00b89'
down_revision: Union[str, None] = 'e2c9de7a572f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proxy', sa.Column('transaction_id', sa.Integer(), nullable=False))
    op.drop_column('proxy', 'password')
    op.drop_column('proxy', 'transaction_ip')
    op.drop_column('proxy', 'user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proxy', sa.Column('user', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('proxy', sa.Column('transaction_ip', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('proxy', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('proxy', 'transaction_id')
    # ### end Alembic commands ###
