"""Change transaction table

Revision ID: 6c97e6492771
Revises: 2a96de9bfb01
Create Date: 2025-05-20 19:37:43.148857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c97e6492771'
down_revision: Union[str, None] = '2a96de9bfb01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_topup_requests_id', table_name='topup_requests')
    op.drop_table('topup_requests')
    op.add_column('transactions', sa.Column('related_ids', sa.String(length=500), nullable=True))
    op.add_column('transactions', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('transactions', sa.Column('external_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'external_id')
    op.drop_column('transactions', 'status')
    op.drop_column('transactions', 'related_ids')
    op.create_table('topup_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('external_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='topup_requests_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='topup_requests_pkey')
    )
    op.create_index('ix_topup_requests_id', 'topup_requests', ['id'], unique=False)
    # ### end Alembic commands ###
