"""add auto_prolong to proxy table

Revision ID: 8c6ecd53a7f1
Revises: 34f73f4781fc
Create Date: 2025-06-06 13:01:36.599580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c6ecd53a7f1'
down_revision: Union[str, None] = '34f73f4781fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proxy', sa.Column('auto_prolong', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proxy', 'auto_prolong')
    # ### end Alembic commands ###
