"""Change proxy table

Revision ID: c8fff0f6150f
Revises: 3eecb3eca8b1
Create Date: 2025-05-22 16:27:57.069960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8fff0f6150f'
down_revision: Union[str, None] = '3eecb3eca8b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proxy', sa.Column('version', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proxy', 'version')
    # ### end Alembic commands ###
