"""Change proxy table

Revision ID: e2c9de7a572f
Revises: 6c97e6492771
Create Date: 2025-05-21 13:28:22.910793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2c9de7a572f'
down_revision: Union[str, None] = '6c97e6492771'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proxy', sa.Column('transaction_ip', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proxy', 'transaction_ip')
    # ### end Alembic commands ###
