"""add auto_prolong to proxy table

Revision ID: e5097488db80
Revises: 2caa90db4780
Create Date: 2025-06-06 11:22:09.805345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5097488db80'
down_revision: Union[str, None] = '2caa90db4780'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proxy', sa.Column('auto_prolong', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proxy', 'auto_prolong')
    # ### end Alembic commands ###
