"""add currency_rates

Revision ID: f7e7a2411c0d
Revises: 8c6ecd53a7f1
Create Date: 2025-10-02 10:37:48.268635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7e7a2411c0d'
down_revision: Union[str, None] = '8c6ecd53a7f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('quote_currency', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_currency_rates_created_at'), 'currency_rates', ['created_at'], unique=False)
    op.create_index(op.f('ix_currency_rates_id'), 'currency_rates', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_currency_rates_id'), table_name='currency_rates')
    op.drop_index(op.f('ix_currency_rates_created_at'), table_name='currency_rates')
    op.drop_table('currency_rates')
    # ### end Alembic commands ###
