PROXY_TYPE_MAPPING = {
    "ipv4": "4",
    "ipv6": "6",
    "ipv4shared": "3"
}
REVERSE_PROXY_TYPE_MAPPING = {v: k for k, v in PROXY_TYPE_MAPPING.items()}
COUNTRY_TRANSLATIONS = {
    "ru": {
        "ru": "Россия",
        "ua": "Украина",
        "us": "США",
        "gb": "Великобритания",
        "de": "Германия",
        "ca": "Канада",
        "nl": "Нидерланды",
        "fr": "Франция",
        "jp": "Япония",
        "it": "Италия",
        "pl": "Польша",
        "es": "Испания",
        "ch": "Швейцария",
        "se": "Швеция",
        "ro": "Румыния",
        "cz": "Чехия",
        "bg": "Болгария",
        "lt": "Литва",
        "lv": "Латвия",
        "sk": "Словакия",
        "fi": "Финляндия",
        "be": "Бельгия",
        "no": "Норвегия",
        "hu": "Венгрия",
        "gr": "Греция",
        "il": "Израиль",
        "ie": "Ирландия",
        "pt": "Португалия",
        "dk": "Дания",
        "si": "Словения",
        "hr": "Хорватия",
        "lu": "Люксембург",
        "md": "Молдова",
        "by": "Беларусь",
        "ee": "Эстония",
        "rs": "Сербия",
        "tr": "Турция",
        "ae": "ОАЭ",
        "in": "Индия",
        "ng": "Нигерия",
        "id": "Индонезия",
        "th": "Таиланд",
        "vn": "Вьетнам",
        "sg": "Сингапур",
        "my": "Малайзия",
        "hk": "Гонконг",
        "za": "ЮАР",
        "br": "Бразилия",
        "ar": "Аргентина",
        "cl": "Чили",
        "au": "Австралия",
        "kz": "Казахстан",
        "ge": "Грузия",
        "tw": "Тайвань",
        "cy": "Кипр",
        "mx": "Мексика",
        "sa": "Саудовская Аравия",
        "eg": "Египет",
        "pk": "Пакистан",
        "bd": "Бангладеш",
        "ph": "Филиппины",
        "ma": "Марокко",
        "tn": "Тунис",
        "al": "Албания",
        "is": "Исландия",
        "mt": "Мальта",
        "mc": "Монако",
        "li": "Лихтенштейн",
        "kr": "Южная Корея",
        "sc": "Сейшелы",
        "kg": "Киргизия",
        "at": "Австрия",
        "tj": "Таджикистан",
        "am": "Армения",
        "tm": "Туркменистан",
        "uz": "Узбекистан",
        "cn": "Китай",
    },
    "en": {
        "ru": "Russia",
        "ua": "Ukraine",
        "us": "United States",
        "gb": "United Kingdom",
        "de": "Germany",
        "ca": "Canada",
        "nl": "Netherlands",
        "fr": "France",
        "jp": "Japan",
        "it": "Italy",
        "pl": "Poland",
        "es": "Spain",
        "ch": "Switzerland",
        "se": "Sweden",
        "ro": "Romania",
        "cz": "Czech Republic",
        "bg": "Bulgaria",
        "lt": "Lithuania",
        "lv": "Latvia",
        "sk": "Slovakia",
        "fi": "Finland",
        "be": "Belgium",
        "no": "Norway",
        "hu": "Hungary",
        "gr": "Greece",
        "il": "Israel",
        "ie": "Ireland",
        "pt": "Portugal",
        "dk": "Denmark",
        "si": "Slovenia",
        "hr": "Croatia",
        "lu": "Luxembourg",
        "md": "Moldova",
        "by": "Belarus",
        "ee": "Estonia",
        "rs": "Serbia",
        "tr": "Turkey",
        "ae": "UAE",
        "in": "India",
        "ng": "Nigeria",
        "id": "Indonesia",
        "th": "Thailand",
        "vn": "Vietnam",
        "sg": "Singapore",
        "my": "Malaysia",
        "hk": "Hong Kong",
        "za": "South Africa",
        "br": "Brazil",
        "ar": "Argentina",
        "cl": "Chile",
        "au": "Australia",
        "kz": "Kazakhstan",
        "ge": "Georgia",
        "tw": "Taiwan",
        "cy": "Cyprus",
        "mx": "Mexico",
        "sa": "Saudi Arabia",
        "eg": "Egypt",
        "pk": "Pakistan",
        "bd": "Bangladesh",
        "ph": "Philippines",
        "ma": "Morocco",
        "tn": "Tunisia",
        "al": "Albania",
        "is": "Iceland",
        "mt": "Malta",
        "mc": "Monaco",
        "li": "Liechtenstein",
        "kr": "South Korea",
        "sc": "Seychelles",
        "kg": "Kyrgyzstan",
        "at": "Austria",
        "tj": "Tajikistan",
        "am": "Armenia",
        "tm": "Turkmenistan",
        "uz": "Uzbekistan",
        "cn": "China"
    }
}
